version: '3'

services:
    nginx:
        image: nginx:1.19.1-alpine
        restart: unless-stopped
        ports:
            - "1000:80"
        env_file:
            - ./.env
        volumes:
            - ./app/www:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
            - ./docker/log/nginx:/var/log/nginx
        networks:
            - reverse-proxy-network
            - internal-network

networks:
    reverse-proxy-network:
        external:
            name: reverse-proxy-network
    internal-network: