version: '3.9'

services:
    nginx:
        build: ./app/
        restart: unless-stopped
        ports:
            - "2000:80"
        env_file:
            - ./.env
        volumes:
            - ./app/www:/var/www
        networks:
            - reverse-proxy-network
            - internal-network

networks:
    reverse-proxy-network:
        external:
            name: reverse-proxy-network
    internal-network: