name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: ls -al
          debug: true
#      - uses: actions/checkout@v2
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1

#      - name: Login to Github package
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.CR_PAT }}

#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: ghcr.io/${{ github.repository }}
#          context: ./app
#          file: ./app/Dockerfile
#          cache-from: type=registry,ref=${{ github.repository }}:latest
#          cache-to: type=inline